name: CICD
on: [push]
jobs:

  validation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install OMSimulator --upgrade
    - name: Generate results
      run: |
        python $(git ls-files 'init_models.py')
    - name: Send control
      run: |
        python $(git ls-files 'run_control.py')
    # - name: Archive results
    #   uses: actions/upload-artifact@v3
    #   with:
    #       name: orchestration-results
    #       path: results.csv

  build-docker:
    needs: validation
    runs-on: windows-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file "docker/Dockerfile" --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:latest
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:latest
          
